jobs:
  update:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        name: Repository dispatch
        run: |-
          gh workflow run build-package.yaml \
            --repo thundertheidiot/nixdots \
            --ref main \
            -f package=nixosConfigurations.vps.pkgs.sodexobot \
            -f flake-input=sodexobot \
            -f vps-deploy=true
name: Update sodexobot in nixdots
"on":
  push: {}
